hmpps.auth.base.url: http://localhost:8081
prison.api.base.url: http://localhost:8082
pathfinder.api.base.url: http://localhost:8083

app.db.url: jdbc:hsqldb:mem:data-compliance-db;sql.syntax_pgs=true;shutdown=false

spring:
  jpa.show-sql: true
  flyway.locations: classpath:db/migration
  security.oauth2.resourceserver.jwt.public-key-location: classpath:local-public-key.pub

offender.retention:
  false.positive.duplicate.check.enabled: false
  image.duplicate.check.enabled: false
  data.duplicate:
    id.check.enabled: false
    db.check.enabled: false
    ap.check.enabled: false

image.recognition.deletion.enabled: false
deletion.grant.enabled: true

server.shutdown: immediate
