data.compliance.request:
  sqs:
    provider: localstack
    queue.name: data_compliance_request_queue
    queue.url: http://localstack:4576/queue/data_compliance_request_queue
    dlq.name: data_compliance_request_dead_letter_queue
    endpoint.url: http://localstack:4576

data.compliance.response:
  sqs:
    provider: localstack
    queue.name: data_compliance_response_queue
    dlq.name: data_compliance_response_dead_letter_queue
    endpoint.url: http://localstack:4576

sns:
  provider: localstack
  topic.arn: arn:aws:sns:eu-west-2:000000000000:offender_events
  endpoint.url: http://localstack:4575
  region: eu-west-2

spring.security.oauth2.resourceserver.jwt.public-key-location: classpath:local-public-key.pub

offender.retention.ap.data.duplicate.check.enabled: true
offender.retention.sql.data.duplicate.check.enabled: true
