management:
  endpoint:
    health.cache.time-to-live: 0
    info.cache.time-to-live: 0

hmpps.auth.base.url: http://localhost:8999
prison.api.base.url: http://localhost:8998
pathfinder.api.base.url: http://localhost:8997

app.db.url: jdbc:hsqldb:mem:data-compliance-db;sql.syntax_pgs=true;shutdown=false


data.compliance.request:
  sqs:
    provider: embedded-localstack
    queue.name: data_compliance_request_queue
    queue.url: http://localhost:4576/queue/data_compliance_request_queue
    dlq.name: data_compliance_request_dead_letter_queue
    endpoint.url: http://localhost:4576

data.compliance.response:
  sqs:
    provider: embedded-localstack
    queue.name: data_compliance_response_queue
    dlq.name: data_compliance_response_dead_letter_queue
    endpoint.url: http://localhost:4576

sns:
  provider: embedded-localstack
  topic.name: offender_events
  topic.arn: arn:aws:sns:eu-west-2:000000000000:offender_events
  endpoint.url: http://localhost:4575
  region: eu-west-2

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
  flyway.locations: classpath:db/migration
  security.oauth2.resourceserver.jwt.public-key-location: classpath:local-public-key.pub
  lifecycle.timeout-per-shutdown-phase: 0s

jwt:
  keystore:
    alias: datacompliance
    password: s3cre3tK3y
  signing.key.pair: MIIKIwIBAzCCCdwGCSqGSIb3DQEHAaCCCc0EggnJMIIJxTCCBXkGCSqGSIb3DQEHAaCCBWoEggVmMIIFYjCCBV4GCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBTpH5+P9bszwZ6B0i05X08iX85VBAIDAMNQBIIEyEm92A0lfDFQPvsmSYZrnyhnAu0kN3w8YurF33kAwFrmM8oVFXe1PYWzMKoiQzjE6Ypny0+lS+hr/jcNIDi5nVeSJx+IWcjmX3GYuM7+pb1e6brLqG2IBw2Pu1++YVQ9peOkt2MYyq6MpU45zx0B6cdYdgTwkdS/puw1mNJfCdDT4fD98Y+b1vXBlhvR7c73sl96PQHRJ5YAmICPlz4LhtJ1Dt0NHLp4T4f6Qr3oaeS7YZATHiHLrxerpZexX/JIwwqI25LLt/LYItzKWZWH7XbBnbuHysDSMyiE7JpvcXbj73p9KghBfY79rsnXUzhd5KFgvmzgH4PFU3qePbzV1FxMzvbqIaTTbdvac2JfHNWxigw13l1tt4fZDiNk2waMpdSYDY71oB+UD88zHx6RDDN0gSIESSBVkKlrzczDIcAL+33WcBMWveHEuQuAeXr26hsopylrKYW4CMDoB4bczrRhs5LqcdqC4djaOyBwWhUVKHgYt99KBmvIrrqw1JDIxryShn7heIjIBxo78LpL/qzunqKSjJdITvWtLuYScrr+PzMTJjchETkRcTno31buggvhfuNFXkf9L0d5KHzFOk0gV8pmAr9uvlqO370bbX7H5vOVQjQcGTWumFZ+zWMcY60J6L+6aaftwSKSRfdBuEOxPG4Uk58MXx3SM3+W4RWpDIp2546FU4fCVdPc7kVRLQ3wYoztc8GtNQPVTMeuCxz3NXBc0vYHwlBy7rEkWqJVmlChfFMoAx+JExm4858YJ0UNd8BTGxIm8I8JCy/vC+7v2EAK6LSND92T2huH4pwcEKV8eiGe3bmJBXJoa08V0GYH8anlKl34/ewJxAZq09VIjCcF949zTxwJkqtpa986SZyhNmK2ngXiuBSXPkBASF4SYFXo/BSqdWKa3oC5s9Kxss/egKhCJmfiAwzT2C6fpdyJR7r+nx51+gZVPE006O23B2YaPUkD/FZhFtlkYZSVovDk2vuLaMrhkmzXtvl32DZSp+u64yJRvS1Kg1NSLyjxcu7sOz7uZbjbcM/8PBD0oYil3H9igagHZyYGtGXFC7dTjpvetZgADA0Lv7eRzbHRFwXfswKfeAB4iIgDnkLveB2zGdA/O1e+tRzLml7THLGLkfh6BAV+H0KrKAia1OIWEXBX18+/x4IUjcvwZY2KBIUY82wHIYuic5ZFWL3E/dEpnpV67IL9FFUsK9EaAr9jZX7GAg1mXMnO91gwFo2L6vvWxynRr0Sj36DQPmxJlmV032Z6WG62m0w90ks+fQpobPZxNniuzvdxMrn9ZuypuM4AN/ygn3HI2xGc9tfs6LleiP3sozVQnHh1lvqC9yVCze7qktCCS6UbsjYdZ6BMm0AE5R8Eu21ag9D5PDggZcpozmpnrf55M1L4AGgHmOxVMguhZxSnZjKZ7la2VDjKVWiiqUK5xRgNRfT+ikmQVieny/BEToWSC5o1Jg1ugeuNxtzLv9IG1OebIf4hjHGWk4Nd3OBsuxXTS6oGVHO1U5ZiWwZDtSuqUGkA+TZpgdgjs9TFqZD+5o316RxDkzwpd+dOQExO1GByjIgCObCFeifiymf3q/XNzJMYP8AIL1zeAT1AhdDPbkwcjuIKvvWmG+Jo+ipu/zFQMCsGCSqGSIb3DQEJFDEeHhwAZABhAHQAYQBjAG8AbQBwAGwAaQBhAG4AYwBlMCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE1ODQzNjczMDEwMjEwggREBgkqhkiG9w0BBwagggQ1MIIEMQIBADCCBCoGCSqGSIb3DQEHATApBgoqhkiG9w0BDAEGMBsEFIY63F0ScwVSE4OfBMyRGaBvpOqEAgMAw1CAggPwUgjNk+LVZ/EaCW16kMm/cgH0CdlKDnZBA7N1Y6q98i9Hqi5qAveclVE4vJKn4xr89N+sFBJIbrBhbPFNIx9VLJlAZzVWjLpeQR37BMjgVTTZMHXNev6GKJHUfSf0kW+TNP4jnQGae957tLlVxZAoh+L5KQ2DGy4yXyEugKLrbtXcfWa2avfczArsE0gI3C7xQtMhKNWUns9JWD2gofmp+Jrj0U8aJ3HMaEDyCJZg3+rVB4t/CECL66PapPkp9NJxKO2Iv29K5yuRE6sevl+G1ltvPdCnTxmGv2qb6NQu6n+viovtnSrhUDu0ksuY1a8c6E0oVeP+nZfRsxhRH8pJO7Megaf6rNQwLCsKVML9dR3rW5moJXb6Xa+JgafPBNiT+q/k41rAlrDiyWw0kEcBImRiI577Thd07WJGsLGMb+2T9X4g/ci12Rbp/OMs0G0CnsvtcZgxbvxDpSRTxLT6VEq+gugjTlMD/l06df3OLXYzd5wkvOD0ZKVNfvkJ7kgfWKlcy9UOrDQdXquHjd+jIf0tMhYgqkPMoasxdXGF48EoIq8Kts7c+weCM2X6JlgjeYZc0fIbWvrKcd6w3kfrlLGUy9pMW9U3/6kTFaly5d0TmaKAyhCu5HNSLrT8as9DuuQB8jfklepHgSdD/Q+BquKqSvHb3qXvWwqSrYkJcSFtzlsnw+yxQyUowBiSixIJPe7sECBdOdIGRtTKG+G3Xsv8WySseT6Y5F7tCQhBHnMHy7ccz/9EPRun1yEYhfG3iidevyigs+L71FfGew9oYCzDYtW2qf8xh74T/kzPb+9pNsXj9VdKC0dWYvhC0ULRvz88f6y5C/K2MJGxIs3MGXyPCYJ1v7nX8nP4eIqYs6d+6XCjPHbmX7XhOmiudpcPuwqvIWA2HvY7lX2GoweuFbgsPYSlPwkVJ2LlBnzug/iI6PAUT+ss1mj+wpY3XrC08h6qrZbFiCdZJe6gxPiGKL0NDtJnpj+Kt3xvyNvdAoOi8UYTl8oop+ED/0Cu8nSh1H3oJ3FcekmAL/I7ZpMNnuwI3mYUTEhxfYLL5hZoeXlLHpuMvqJG3oYNk8SLq26j8zIh8P6AT7z5WH3TV0OHGxpkRNL29x5vZnZdqqbcZhlLs88SjZ6hlf6ft/OuV+aSV72mEwAJvcUlMAE92T9SyBtrlzcet5pXkKkcqrlh6easCBFL6GSXUc+XWtaqR0Enjb8SQ+fsKLAPJ3GW8Xm5szKecDthFTR9ShB+7MHF3ewmYmepvMsYrIk4rtdPg96px8jpsdD++gEZIXcHz0cXDcyY0bpVQJQbnuISG9y9PuZ+s4l9oj32jufLqtY9QNczMD4wITAJBgUrDgMCGgUABBRnaVniWXMjYd5bJ/P9icH+AbYOjAQUNhW/LlzoQOLueUy31nSv5kXH/d0CAwGGoA==

offender.retention:
  false.positive.duplicate.check.enabled: false
  image.duplicate.check.enabled: false
  data.duplicate:
    id.check.enabled: true
    db.check.enabled: true
    ap.check.enabled: false

deletion.grant.enabled: true
offender.deletion.review.required: false
image.recognition.deletion.enabled: true

server.shutdown: immediate
